# Generated by Django 2.0.5 on 2018-05-24 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostCluster', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNO', models.CharField(max_length=32)),
                ('cabinetNO', models.CharField(max_length=32)),
                ('bladeBoxNO', models.CharField(max_length=32)),
                ('bladeNO', models.CharField(max_length=32)),
                ('hostName', models.CharField(max_length=32)),
                ('serviceIP', models.GenericIPAddressField()),
                ('manageIP', models.GenericIPAddressField()),
                ('storageIP', models.GenericIPAddressField()),
                ('hardware', models.CharField(max_length=64)),
                ('service', models.CharField(max_length=32)),
                ('powerOnTime', models.CharField(max_length=32)),
                ('powerOffTime', models.CharField(max_length=32)),
                ('checkOnline', models.CharField(max_length=32)),
                ('runTime', models.CharField(max_length=32)),
                ('hostCluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManager.Clusters')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
