# Generated by Django 2.0.6 on 2018-07-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0004_auto_20180702_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='runTime',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
