# Generated by Django 2.0.7 on 2018-07-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0008_auto_20180712_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusters',
            old_name='hostCluster',
            new_name='clusterName',
        ),
    ]
