# Generated by Django 2.0.7 on 2018-07-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0009_auto_20180712_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='hostCluster',
            new_name='clusterName',
        ),
    ]
