# Generated by Django 2.0.7 on 2018-07-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0010_auto_20180712_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerOnTimeHistory', models.DateTimeField(null=True)),
                ('powerOffTimeHistory', models.DateTimeField(null=True)),
                ('hostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManager.Host')),
            ],
        ),
        migrations.AlterField(
            model_name='clusters',
            name='contactEmail',
            field=models.EmailField(max_length=32, null=True),
        ),
    ]
