# Generated by Django 2.0.7 on 2018-07-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0012_auto_20180716_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostpowerhistory',
            old_name='hostId',
            new_name='host',
        ),
    ]
