# Generated by Django 2.0.7 on 2018-07-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0013_auto_20180716_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='powerCycleTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hostpowerhistory',
            name='powerCycleTimeHistory',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hostpowerhistory',
            name='runTimeHistory',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
