# Generated by Django 2.0.7 on 2018-07-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0014_auto_20180716_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostpowerhistory',
            old_name='powerCycleTimeHistory',
            new_name='powerCycleTimes',
        ),
    ]
