# Generated by Django 2.0.7 on 2018-07-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0015_auto_20180716_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostpowerhistory',
            name='powerCycleTimes',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
