# Generated by Django 2.1 on 2018-08-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0016_auto_20180716_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='billing',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='hostpowerhistory',
            name='powerCycleTimes',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
