# Generated by Django 2.1 on 2018-08-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0017_auto_20180822_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='billing',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
