# Generated by Django 2.1 on 2018-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0018_auto_20180827_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='billing',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
