# Generated by Django 2.1 on 2018-08-28 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0019_auto_20180827_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billingNumber', models.CharField(max_length=32, null=True)),
                ('billingPrice', models.CharField(max_length=32, null=True)),
                ('billingStartTime', models.CharField(max_length=32, null=True)),
                ('billingStopTime', models.CharField(max_length=32, null=True)),
                ('clusterName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManager.Clusters')),
            ],
        ),
        migrations.CreateModel(
            name='BillingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clusterName', models.CharField(max_length=32, null=True)),
                ('deviceNumber', models.CharField(max_length=32, null=True)),
                ('billingNumber', models.CharField(max_length=32, null=True)),
                ('billingPrice', models.CharField(max_length=32, null=True)),
                ('billingStartTime', models.CharField(max_length=32, null=True)),
                ('billingStopTime', models.CharField(max_length=32, null=True)),
                ('billingNowTime', models.CharField(max_length=32, null=True)),
                ('billingCount', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
