# Generated by Django 2.1 on 2018-08-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0020_billing_billinghistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='billing',
            new_name='billingStatus',
        ),
        migrations.AddField(
            model_name='host',
            name='powerStatus',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
