# Generated by Django 2.1 on 2018-09-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0021_auto_20180829_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='monitorStatus',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
