# Generated by Django 2.1 on 2018-09-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0022_host_monitorstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostpowerhistory',
            name='powerCycleTimes',
            field=models.IntegerField(default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='hostpowerhistory',
            name='runTimeHistory',
            field=models.DurationField(max_length=32, null=True),
        ),
    ]
