# Generated by Django 2.1 on 2018-09-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0023_auto_20180904_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostpowerhistory',
            name='powerCycleTimes',
            field=models.IntegerField(default='0'),
        ),
    ]
