# Generated by Django 2.1 on 2018-09-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0025_auto_20180904_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostpowerhistory',
            name='powerCycleTimes',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
