# Generated by Django 2.1 on 2018-09-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0026_auto_20180904_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostpowerhistory',
            name='powerCycleTimes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hostpowerhistory',
            name='runTimeHistory',
            field=models.DurationField(max_length=32, null=True),
        ),
    ]
