# Generated by Django 2.1 on 2018-09-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0027_auto_20180904_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='runTime',
            field=models.DurationField(max_length=32, null=True),
        ),
    ]
