# Generated by Django 2.1 on 2018-09-04 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0028_auto_20180904_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostCountPowerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countRunTimeHistory', models.DurationField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='runTime',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='hostpowerhistory',
            name='runTimeHistory',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='hostcountpowerhistory',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManager.Host'),
        ),
    ]
