# Generated by Django 2.1 on 2018-09-11 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0029_auto_20180904_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkPowerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIP', models.GenericIPAddressField(null=True)),
                ('checkTime', models.DurationField(null=True)),
                ('checkResult', models.CharField(max_length=32, null=True)),
                ('checkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManager.Host')),
            ],
        ),
    ]
