# Generated by Django 2.1 on 2018-09-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0030_checkpowerstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpowerstatus',
            name='checkID',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
