# Generated by Django 2.1 on 2018-09-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0032_auto_20180911_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpowerstatus',
            name='checkTime',
            field=models.DateTimeField(null=True),
        ),
    ]
