# Generated by Django 2.1 on 2018-09-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0034_auto_20180911_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpowerstatus',
            name='checkTaskID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
