# Generated by Django 2.1 on 2018-09-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0035_auto_20180911_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpowerstatus',
            name='tags',
            field=models.ManyToManyField(to='HostManager.Host'),
        ),
    ]
