# Generated by Django 2.1 on 2018-09-11 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0036_checkpowerstatus_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpowerstatus',
            name='checkHostID',
        ),
        migrations.RemoveField(
            model_name='checkpowerstatus',
            name='tags',
        ),
        migrations.AddField(
            model_name='checkpowerstatus',
            name='checkHost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HostManager.Host'),
        ),
    ]
