# Generated by Django 2.1 on 2018-09-12 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0040_auto_20180911_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkPowerOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkTaskID', models.CharField(max_length=255, null=True)),
                ('checkHostIP', models.GenericIPAddressField(null=True)),
                ('checkTime', models.DateTimeField(null=True)),
                ('checkResult', models.CharField(max_length=32, null=True)),
                ('checkHost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HostManager.Host')),
            ],
        ),
        migrations.CreateModel(
            name='checkPowerOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkTaskID', models.CharField(max_length=255, null=True)),
                ('checkHostIP', models.GenericIPAddressField(null=True)),
                ('checkTime', models.DateTimeField(null=True)),
                ('checkResult', models.CharField(max_length=32, null=True)),
                ('checkHost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HostManager.Host')),
            ],
        ),
        migrations.RenameModel(
            old_name='checkPowerStatus',
            new_name='checkPowerFail',
        ),
    ]
