# Generated by Django 2.1 on 2018-10-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0041_auto_20180912_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='installStatus',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
