# Generated by Django 2.1 on 2018-10-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0042_host_installstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallSystemHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installStartTimeHistory', models.DateTimeField(null=True)),
                ('installEndTimeHistory', models.DateTimeField(null=True)),
                ('installRunTimeHistory', models.DurationField(null=True)),
                ('installSystemStatus', models.CharField(default='0', max_length=1)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManager.Host')),
            ],
        ),
    ]
