# Generated by Django 2.1 on 2018-10-26 03:12

from django.db import migrations, models
import django.db.models.deletion
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0043_installsystemhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostMac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipmiMac', macaddress.fields.MACAddressField(blank=True, integer=True, null=True, unique=True)),
                ('pxeMac', macaddress.fields.MACAddressField(blank=True, integer=True, null=True, unique=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManager.Host')),
            ],
        ),
    ]
