# Generated by Django 2.1 on 2018-10-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0044_hostmac'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='pingStatus',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
