# Generated by Django 2.1 on 2018-11-01 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0045_host_pingstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=64, null=True)),
                ('remark', models.CharField(max_length=64, null=True)),
                ('purpose', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='manufacturer',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hostproperty',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManager.Host'),
        ),
    ]
