# Generated by Django 2.1 on 2018-11-01 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0046_auto_20181101_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostHumanProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=64, null=True)),
                ('remark', models.CharField(max_length=64, null=True)),
                ('purpose', models.CharField(max_length=64, null=True)),
                ('department', models.CharField(max_length=64, null=True)),
                ('principal', models.CharField(max_length=64, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManager.Host')),
            ],
        ),
        migrations.CreateModel(
            name='HostPartProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpuNum', models.IntegerField(max_length=64, null=True)),
                ('cpuHz', models.CharField(max_length=64, null=True)),
                ('cpuCore', models.IntegerField(max_length=64, null=True)),
                ('memory', models.IntegerField(max_length=64, null=True)),
                ('diskCapacity', models.IntegerField(max_length=64, null=True)),
                ('diskNum', models.IntegerField(max_length=64, null=True)),
                ('diskRaid', models.CharField(max_length=64, null=True)),
                ('networkAdapter', models.IntegerField(max_length=64, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostManager.Host')),
            ],
        ),
        migrations.CreateModel(
            name='HostTimeProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasingDate', models.DateTimeField(null=True)),
                ('acceptanceDate', models.DateTimeField(null=True)),
                ('warrentyPeriod', models.IntegerField(max_length=64, null=True)),
                ('warrentyStartDate', models.DateTimeField(null=True)),
                ('warrentyEndDate', models.DateTimeField(null=True)),
                ('useStartDate', models.DateTimeField(null=True)),
                ('useEndDate', models.DateTimeField(null=True)),
                ('lifeCycle', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hostproperty',
            name='host',
        ),
        migrations.DeleteModel(
            name='HostProperty',
        ),
    ]
