# Generated by Django 2.1 on 2018-11-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0047_auto_20181101_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostpartproperty',
            name='cpuCore',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hostpartproperty',
            name='cpuNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hostpartproperty',
            name='diskCapacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hostpartproperty',
            name='diskNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hostpartproperty',
            name='memory',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hostpartproperty',
            name='networkAdapter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hosttimeproperty',
            name='warrentyPeriod',
            field=models.IntegerField(null=True),
        ),
    ]
