# Generated by Django 2.1 on 2018-11-01 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0048_auto_20181101_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosttimeproperty',
            name='host',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='HostManager.Host'),
            preserve_default=False,
        ),
    ]
