# Generated by Django 2.1 on 2018-11-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0049_hosttimeproperty_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosthumanproperty',
            name='host',
        ),
        migrations.DeleteModel(
            name='HostHumanProperty',
        ),
    ]
