# Generated by Django 2.1 on 2018-11-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0051_hosthumanproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosthumanproperty',
            name='vendor',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
