# Generated by Django 2.1.3 on 2018-11-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0052_auto_20181101_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
