# Generated by Django 2.1.3 on 2018-11-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0054_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
