# Generated by Django 2.1.3 on 2018-11-26 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0055_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='clusterName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HostManager.Clusters'),
        ),
    ]
