# Generated by Django 2.1.3 on 2018-11-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0056_auto_20181126_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=32, null=True)),
                ('cabinetNumber', models.CharField(max_length=32, null=True)),
                ('floorName', models.CharField(max_length=32, null=True)),
                ('roomArea', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
