# Generated by Django 2.1.3 on 2018-11-27 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0058_auto_20181127_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='roomNO',
        ),
        migrations.AddField(
            model_name='host',
            name='roomNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HostManager.Rooms'),
        ),
    ]
