# Generated by Django 2.1.3 on 2018-11-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0059_auto_20181127_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='roomNumber',
            new_name='roomName',
        ),
    ]
