# Generated by Django 2.1.3 on 2018-11-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0060_auto_20181127_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='billingStatus',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='installStatus',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='monitorStatus',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='pingStatus',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='powerStatus',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
    ]
