# Generated by Django 2.1.3 on 2018-11-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0061_auto_20181128_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osName', models.CharField(max_length=32, null=True)),
                ('osNumber', models.CharField(max_length=32, null=True)),
                ('osBit', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
