# Generated by Django 2.1.4 on 2018-12-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0063_auto_20181219_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installsystemhistory',
            name='installSystemResult',
        ),
    ]
