# Generated by Django 2.1.4 on 2018-12-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0064_remove_installsystemhistory_installsystemresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='installsystemhistory',
            name='installSystemResult',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='installsystemhistory',
            name='installSystemStatus',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
