# Generated by Django 2.1.4 on 2018-12-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostManager', '0066_auto_20181219_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, null=True)),
                ('actionip', models.CharField(max_length=32, null=True)),
                ('content', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='installsystemhistory',
            name='installSystemResult',
        ),
    ]
