# Current docs for the syntax of this file are at:
#  https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted.md

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

queue:
  name: Hosted Linux Preview

trigger:
  branches:
    include:
    - master
    - 3.7
    - 3.6
  paths:
    include:
    - Doc/*

#variables:

steps:
- checkout: self
  clean: true
  fetchDepth: 5

- task: UsePythonVersion@0
  displayName: 'Use Python 3.6 or later'
  inputs:
    versionSpec: '>=3.6'

- script: python -m pip install sphinx~=1.6.1 blurb python-docs-theme
  displayName: 'Install build dependencies'

- script: make check suspicious html PYTHON=python
  workingDirectory: '$(build.sourcesDirectory)/Doc'
  displayName: 'Build documentation'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    PathToPublish: '$(build.sourcesDirectory)/Doc/build'
    ArtifactName: build
    publishLocation: Container
